name: Deploy to GitHub Pages

on:
  push:
    branches: [main]          # main ブランチに push されたら実行
  workflow_dispatch:          # 手動トリガも可

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ① リポジトリ取得
      - name: Checkout
        uses: actions/checkout@v4

      # ② docs/ フォルダを Pages アーティファクトとしてアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      # ③ GitHub Pages へデプロイ
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
